### ISSUE TITLE
Floating point values parsing using the local culture

### ISSUE THREAD

**Issue by PiKeyAr** [sonicretro/mod-loader-common#9]
Causes [this](https://github.com/X-Hax/sadx-mod-loader/issues/66).

Happens on system locales where decimal comma is used instead of decimal dot. This is because the floats' text representation is parsed in the serializer using the local culture.

Possible solution: .NET 4.5 and above allows to set `CultureInfo.DefaultThreadCurrentCulture`. However, at the moment all Mod Managers are on 4.0 which doesn't have this feature.

**Comment by MainMemory** [comment]
Alternate solution: send `float` values to the PropertyGrid as strings and parse the value manually.
